# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate rust-i18n

Name:           rust-rust-i18n
Version:        3.1.5
Release:        %autorelease
Summary:        Rust I18n is use Rust codegen for load YAML file storage translations on compile time, and give you a t! macro for simply get translation texts

License:        MIT
URL:            https://crates.io/crates/rust-i18n
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Rust I18n is use Rust codegen for load YAML file storage translations on
compile time, and give you a t! macro for simply get translation texts.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/DEVELOPMENT.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+log-miss-tr-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+log-miss-tr-devel %{_description}

This package contains library source intended for building other packages which
use the "log-miss-tr" feature of the "%{crate}" crate.

%files       -n %{name}+log-miss-tr-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
